### ISSUE TITLE
Expose "raw" MediaCapture Object

### ISSUE THREAD

**Issue by ghandmann** [webrtc-uwp/webrtc-windows#11]
Hi There,
we currently experiment with the Hololens and WebRTC. Therefore we use this project as WebRTC library.

In order to enable the "mixed reality capture" of the Hololens we would need to have access to the raw [MediaCapture](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture) object to call "AddVideoEffectAsync". Currently i can't see any way this is exposed by your library. It looks like, that the needed object is created in [PeerConnectionInterface.cc Line 601](https://github.com/webrtc-uwp/webrtc-windows/blob/14e7b71ce361e877d3ec43e9df0ca85802bcebb6/org/webrtc/wrapper/PeerConnectionInterface.cc#L601)

Do you have any suggestion for us on how to access the needed information? 

Thanks,
Sven

**Comment by jamescadd** [comment]
Hi Sven,

We have an open issue to enabled mixed reality capture for HoloLens.  It should be ready in approximately 1 month.  I'll leave this issue open and comment as we make progress, or feel free to reach out at jacadd@microsoft.com to discuss further.

Thanks,
James

**Comment by Noemata** [comment]
Could you please provide updated information on this.

**Comment by Noemata** [comment]
I'm presently looking through Media.h and Media.cc in order to find a place where we could wire in the HoloLens MediaCapture capability.  It's not obvious what needs to be tweaked.  Any suggestions since this has become a languishing item.  We'll do the work, we just need some hints.

**Comment by DanAndersen** [comment]
Hi,
Has there been some development on enabling mixed reality capture? I am currently needing to use WebRTC for a HoloLens app, in which each frame being sent from the HoloLens contains a payload of metadata of the estimated pose of that frame.

**Comment by jamescadd** [comment]
@Noemata @DanAndersen We're close, but have run into an issue that's preventing MRC from working.  I should have an update for this thread in the next day or 2, will keep everyone posted as this has been outstanding for some time.

**Comment by Noemata** [comment]
Any updates on this, given we're past the next day or 2.  Sorry to be pestering about this, but we need to decide how to proceed.

**Comment by jamescadd** [comment]
Thanks for suggesting that alternative approach, and I can see how the transforms would be important. Mosa is working on this now, will let you know when it's ready. Perhaps it will also alleviate the audio issue.
________________________________

**Comment by Noemata** [comment]
Thank you very much for the quick turn around on your reply.  Using the CameraProjectionTransform and CameraViewTransform approach allows us to do the compositing ourselves through several different approaches and eliminates bogging down the HoloLens side with this task.  If you do continue to proceed with the MRC approach on the HoloLens, please make it a feature we can disable, but always provide these Camera transform details on the HoloLens as there's no performance hit associated with these calls and it does allow us to then do the compositing through other means.

**Comment by adrianimajion** [comment]
Hey, just wanted to check how progress is looking for exposing CameraProjectionTransform and CameraViewTransform. @morosev regardless of MRC this would be really valuable for us. Thanks

**Comment by jamescadd** [comment]
Hi all, we've determined that the likely cause of MRC not working is the D3D context management of UWP apps.  The quickest resolution is to separate out a Unity only app which, after which we expect the MRC code to just work.  Exposing the transforms per the above will be next up when that's complete.  Thanks!

**Comment by jamescadd** [comment]
Latest bits are below - tested and working on PC but pending testing on HoloLens.  MRC code is in place but not yet tested, perf hasn't been verified either.

https://github.com/ortclib/ortclib-sdk/tree/Mosa/20180320-peercc-unity

- The desktop app should be the standard PeerConnection M62 build
- Codec is forced to H.264 and settings are hard coded.  Peer selection list isn't functional
- Enter the signaling server IP into the text box (HoloLens keyboard isn't implemented yet so use the virtual input feature on the device portal)
- Click the connect button in the Unity app, peer should show up on desktop
- Click the call button on Unity app (this app must initiate for now)

**Comment by jamescadd** [comment]
Issue moved to [webrtc-uwp/webrtc-uwp-sdk #30](https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/30) via [**ZenHub**](https://www.zenhub.com/)
