### ISSUE TITLE
Expose PeerConnectionFactory API in UWP SDK

### ISSUE THREAD

**Issue by mstyura** [webrtc-uwp/webrtc-windows#15]
The official SDK for ObjC and Android exposes PeerConnectionFactory in its API, providing more control over how PeerConnection is created and configured. This UWP SDK does not expose peer connection factory at all, which makes impossible some use cases for "native" apps: for example, I'd like to control if encryption is enabled/disable, and if loopback adapter is emitted by ICE (PeerConnectionFactoryInterface::Options).

**Comment by jamescadd** [comment]
Issue moved to [webrtc-uwp/webrtc-uwp-sdk #28](https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/28) via [**ZenHub**](https://www.zenhub.com/)
