### ISSUE TITLE
Which version of "webrtc for uwp" contains Media.CreateMediaSource? 

### ISSUE THREAD

**Issue by saschenjka** [webrtc-uwp/webrtc-windows#16]
I am using this simple webrtc example: [UWP_WebRTC_NoSignalling](https://gitlab.ida.liu.se/lilbl552/UWP_WebRTC_NoSignalling/tree/master/VideoStreamWebRTC).
It contains a line
`var source = _media.CreateMediaSource(selectedVideoTrac, _localStream.Id);`
 This method is not available in the current version of **'webrtc for uwp'**

The author says I can download **webrtc-uwp** with **Nuget**.
So I installed with **Nuget** with: 
`Install-Package WebRTC -Version 1.62.0.7`
As I try to build, I receive message:

```
Error	CS1061:	"Media" contains no definition for "CreateMediaSource", and no extension method CreateMediaSource, accepting a first argument of type "Media" could be found (are you missing a using directive or an assembly reference?)	
Project: VideoStreamWebRTC	
File: C:\Workspace\MAS\UWP\webrtc_no_signal\VideoStreamWebRTC\MainPage.xaml.cs	
Line: 87
```	
And the author says, he used another wrapper for webrtc [wrapper-(tree:28f25e2b2b)](https://github.com/webrtc-uwp/webrtc-windows/tree/28f25e2b2bac31884592911eacd286a6120b9c2e/org/webrtc/wrapper). And this wrapper [contains CreateMediaSource](https://github.com/webrtc-uwp/webrtc-windows/blob/28f25e2b2bac31884592911eacd286a6120b9c2e/org/webrtc/wrapper/Media.h) . But the standard wrapper from master branch, [doesn't contain CreateMediaSource](https://github.com/webrtc-uwp/webrtc-windows/blob/master/org/webrtc/wrapper/Media.h). 
I can't ask him directly, because his private university github **gitlab.ida.liu.se** doesn't allow to ask questions.

So I ask here, is there a way to install this old **webrtc-for-uwp-wrapper** with **Nuget**, so I can use the example with "**CreateMediaSource**"? Which version shall I install?

**Comment by saschenjka** [comment]
I found the actual function from Media.h, which replaced CreateMediaSource. 
In this example you should write:
` _media.AddVideoTrackMediaElementPair(selectedVideoTrac, LocalVideo, _localStream.Id);`

**Comment by jamescadd** [comment]
It looks like you've answered your question, but if you needed to go back to the version used in the sample referenced you would specify 1.54.2 as the version when installing the NuGet package (see project.json in the sample).

There was significant rework in the media pipeline for M62 to improve performance, so rather than go back to 1.54 I would recommend continuing to work with the current package version.
