### ISSUE TITLE
Change audio volume

### ISSUE THREAD

**Issue by monsdar** [webrtc-uwp/webrtc-windows#18]
Hey,

As far as I can see there's no way to change the audio volume of the RemoteStream? Is there a way that isn't obvious to me, or is it needed to add code to the wrapper for this?

Thanks a lot
Nils

**Comment by jamescadd** [comment]
Issue moved to [webrtc-uwp/webrtc-uwp-sdk #27](https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/27) via [**ZenHub**](https://www.zenhub.com/)
