### ISSUE TITLE
Support for Win32 .NET

### ISSUE THREAD

**Issue by robert-virkus** [webrtc-uwp/webrtc-windows#3]
Hi everyone,

do you plan to support Win32 .NET, too? Currently certain features such as capturing screens of other apps require me to stick to Win32 for now.
Thanks in advance,
 Robert

**Comment by Terricide** [comment]
+1 for support for .NET desktop app

**Comment by jamescadd** [comment]
Screen capture is available in UWP as of RS4: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture

For .NET desktop support we have a basic DataChannel sample available today if that's all you need.  Audio/video support is planned but we don't have a timeframe yet.

**Comment by jamescadd** [comment]
Issue moved to [webrtc-uwp/webrtc-uwp-sdk #36](https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/36) via [**ZenHub**](https://www.zenhub.com/)
