### ISSUE TITLE
Why RawVideoSource can't return the peer video data?

### ISSUE THREAD

**Issue by youshinki** [webrtc-uwp/webrtc-windows#4]
I want get the remote yuv data, so i used RawVideoSource in OnAddRemoteStream event func.
But this RawVideoSource.OnRawVideoFrame event func did not return the data what i wanted.

This is  what i got:
uint __param0 = 640
uint __param1 = 480,
byte[] __param2 ={0}
uint __param3 = 0
byte[] __param4 = {0}
uint __param5 = 0
byte[] __param6 = {0}
uint __param7 = 0

Please help!!
ps: i'm using nuget webrtc lib version 1.54.2

**Comment by jamescadd** [comment]
The RawVideoSource.OnRawVideoFrame event only returns data for VP8 and VP9 codecs.  It's likely you were using H.264 which we currently do not include a decoder for due to relying on hardware encode/decode through MediaFoundation.
