### ISSUE TITLE
Add setConfiguration() 

### ISSUE THREAD

**Issue by zombiecong** [webrtc-uwp/webrtc-windows#8]
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setConfiguration

thx

**Comment by jamescadd** [comment]
@robin-raymond this appears to have become available in Chrome as of M56, but I don't see it in the WinRT API surface.  Is it possible to add, maybe the IDL is missing?

**Comment by jamescadd** [comment]
Issue moved to [webrtc-uwp/webrtc-uwp-sdk #33](https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/33) via [**ZenHub**](https://www.zenhub.com/)
