### ISSUE TITLE
Support for RTCOfferOptions (specifically offerToReceiveVideo)

### ISSUE THREAD

**Issue by rogeru** [webrtc-uwp/webrtc-windows#9]
I am trying to create an offer with recv-only video which can be achieved via RTCOfferOption offerToReceiveVideo while not sending video yourself. This is supported by Chrome and Firefox.

If there any plan to support this?
 
http://w3c.github.io/webrtc-pc/#configuration-data-extensions

**Comment by jamescadd** [comment]
Issue moved to [webrtc-uwp/webrtc-uwp-sdk #32](https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/32) via [**ZenHub**](https://www.zenhub.com/)
